# Site settings
title: 史丹青的博客
header-img: img/home-bg.jpg
email: sdq1990@hotmail.com
description: "分享生活"
baseurl: ""
url: "http://sdq.github.io"
twitter_username: 
github_username:  sdq
facebook_username:  shidanqing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
